version: "3.8"

networks:
  test:

services:
  nginx:
    container_name: nginx-container
    image: nginx:1.18
    restart: always
    ports:
      - 81:81
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - test

  app:
    image: nelucristian/metal-investment:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8082"
    environment:
      METAL_INVESTMENT_MAIL_FROM: $METAL_INVESTMENT_MAIL_FROM
      METAL_INVESTMENT_MAIL_PASSWORD: $METAL_INVESTMENT_MAIL_PASSWORD
      METAL_INVESTMENT_MAIL_PORT: $METAL_INVESTMENT_MAIL_PORT
      METAL_INVESTMENT_MAIL_HOST: $METAL_INVESTMENT_MAIL_HOST
      METAL_INVESTMENT_ENCODER_SECRETE: $METAL_INVESTMENT_ENCODER_SECRETE
    networks:
      - test
    command: java -jar /target/metal-investment-0.0.1.jar


  docker-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: metals
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3307:3306'
    healthcheck:
      test: "/usr/bin/mysql --user=test --password=test--execute \"SHOW DATABASES;\""
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - test
